#!/usr/bin/env python3
"""
ibvs_action_server.py -- ROS2 Action Server: Visual inspection pipeline.

Two-stage centering (matches ibvs_pipeline.py logic):
  Stage 1 -- COARSE (Insta360)
    - YOLO detects object in panoramic view
    - Degree-4 calibrated formula -> servo angles
    - Pan-tilt moves to point Logitech at the object

  Stage 2 -- FINE IBVS (Logitech)
    - YOLO detects object in Logitech view
    - PID control loop centers object (KP=0.12, KI=0.002, KD=0.02)
    - Max 3 deg/step, convergence at 10px error

  Capture
    - 4 images from Logitech once centred
    - Publish via MQTT

Debug topics (view in RViz2):
  /visual_inspection/insta360/debug   -- Insta360 with YOLO bounding boxes
  /visual_inspection/logitech/debug   -- Logitech with YOLO bounding boxes

Action:
  /visual_inspection/inspect_objects  (visual_inspection_interfaces/InspectObjects)
"""

import rclpy
from rclpy.node import Node
from rclpy.action import ActionServer, CancelResponse, GoalResponse
from rclpy.callback_groups import ReentrantCallbackGroup

from sensor_msgs.msg import Image
from std_msgs.msg import Int16MultiArray
from cv_bridge import CvBridge

from visual_inspection_interfaces.action import InspectObjects

import cv2
import numpy as np
import time
import os
import threading


# ---------------------------------------------------------------------------
# Calibration -- degree-4 polynomial from calibration_config.py
# Generated by calibration_analysis_v2_script.py
# ---------------------------------------------------------------------------

def calculate_pan(x, y):
    val = 155.6668858701
    val += 0.4560199871 * x
    val += 0.7342655133 * y
    val += -0.0035976159 * (x**2)
    val += -0.0043827793 * (x*y)
    val += -0.0084661672 * (y**2)
    val += 0.0000057403 * (x**3)
    val += 0.0000133400 * (x**2*y)
    val += 0.0000101783 * (x*y**2)
    val += 0.0000536484 * (y**3)
    val += -0.0000000029 * (x**4)
    val += -0.0000000106 * (x**3*y)
    val += -0.0000000180 * (x**2*y**2)
    val += 0.0000000082 * (x*y**3)
    val += -0.0000001569 * (y**4)
    return float(np.clip(val, 0, 180))


def calculate_tilt(x, y):
    val = 113.6717028380
    val += 0.3335993613 * x
    val += -0.6916488737 * y
    val += -0.0008407415 * (x**2)
    val += -0.0009024326 * (x*y)
    val += 0.0084145572 * (y**2)
    val += 0.0000005454 * (x**3)
    val += 0.0000028613 * (x**2*y)
    val += 0.0000022977 * (x*y**2)
    val += -0.0000683027 * (y**3)
    val += 0.0000000001 * (x**4)
    val += -0.0000000038 * (x**3*y)
    val += 0.0000000088 * (x**2*y**2)
    val += -0.0000000351 * (x*y**3)
    val += 0.0000002091 * (y**4)
    return float(np.clip(val, 20, 160))


def clamp_servo(val):
    return int(max(0, min(180, round(val))))


# ---------------------------------------------------------------------------
# YOLO loader
# ---------------------------------------------------------------------------

def load_yolo(engine_path):
    try:
        from ultralytics import YOLO
        if os.path.exists(engine_path):
            model = YOLO(engine_path)
            print(f'[ibvs_action_server] YOLO loaded: {engine_path}')
        else:
            pt_path = engine_path.replace('.engine', '.pt')
            model = YOLO(pt_path)
            print(f'[ibvs_action_server] YOLO fallback to PT weights: {pt_path}')
        return model
    except Exception as e:
        print(f'[ibvs_action_server] YOLO load failed: {e}')
        return None


# ---------------------------------------------------------------------------
# Action Server Node
# ---------------------------------------------------------------------------

class IBVSActionServer(Node):

    ENGINE_PATH     = os.path.expanduser('~/Documents/Visual_Inspection_ws/weights/yolo11n.engine')
    YOLO_CONF       = 0.5

    # IBVS PID (from ibvs_pipeline.py Config)
    KP              = 0.12
    KI              = 0.002
    KD              = 0.02
    MAX_STEP_DEG    = 3.0    # max servo step per iteration (degrees)
    SLOW_ZONE_PX    = 15.0   # slow down when error < this
    DEADBAND_PX     = 2.0    # don't move if error < this
    IBVS_TOL_PX     = 10.0   # converged when error < this
    IBVS_MAX_ITER   = 200
    IBVS_CONF       = 0.3    # lower conf for IBVS (object may be partially occluded)
    SERVO_DELAY     = 0.033  # seconds between servo commands (~30Hz)
    IBVS_FIRST_DET_TIMEOUT = 5.0  # seconds to wait for first detection in Logitech

    # Logitech frame centre (640x480)
    CX_LOGI         = 320.0
    CY_LOGI         = 240.0
    FX_LOGI         = 640.0  # approximate focal length in pixels
    FY_LOGI         = 640.0

    IMAGES_PER_OBJ  = 4
    CAPTURE_DELAY   = 0.5
    RECENTER_WAIT   = 2.0    # wait after coarse move for servos to reach position

    def __init__(self):
        super().__init__('ibvs_action_server')
        self.bridge   = CvBridge()
        self.cb_group = ReentrantCallbackGroup()

        # Latest frames (thread-safe)
        self._lock_insta  = threading.Lock()
        self._lock_logi   = threading.Lock()
        self._frame_insta = None
        self._frame_logi  = None

        # Subscribers
        self.create_subscription(
            Image, '/visual_inspection/insta360/image_raw',
            self._cb_insta, 10, callback_group=self.cb_group)
        self.create_subscription(
            Image, '/visual_inspection/logitech/image_raw',
            self._cb_logi, 10, callback_group=self.cb_group)

        # Publishers
        self.servo_pub       = self.create_publisher(Int16MultiArray, '/servo/pan_tilt', 10)
        self.debug_insta_pub = self.create_publisher(Image, '/visual_inspection/insta360/debug', 10)
        self.debug_logi_pub  = self.create_publisher(Image, '/visual_inspection/logitech/debug', 10)

        # YOLO
        self.get_logger().info('Loading YOLO model...')
        self.model = load_yolo(self.ENGINE_PATH)
        if self.model:
            self.get_logger().info('YOLO model ready')
        else:
            self.get_logger().error('YOLO load failed')

        # YOLO lock (prevent concurrent inference between timer and goal)
        self._yolo_lock   = threading.Lock()
        self._goal_active = False

        # Action server
        self._action_server = ActionServer(
            self, InspectObjects,
            '/visual_inspection/inspect_objects',
            execute_callback=self.execute_callback,
            goal_callback=self.goal_callback,
            cancel_callback=self.cancel_callback,
            callback_group=self.cb_group
        )

        # Continuous detection timer -- publishes debug images every 0.5s for RViz
        self.create_timer(0.5, self._debug_timer_cb)

        self.get_logger().info('Action server ready at /visual_inspection/inspect_objects')
        self.get_logger().info('Debug topics: /visual_inspection/insta360/debug  /visual_inspection/logitech/debug')

    # ---- Camera callbacks ---------------------------------------------------

    def _cb_insta(self, msg):
        frame = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        with self._lock_insta:
            self._frame_insta = frame

    def _cb_logi(self, msg):
        frame = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        with self._lock_logi:
            self._frame_logi = frame

    def _get_insta_frame(self):
        with self._lock_insta:
            return self._frame_insta.copy() if self._frame_insta is not None else None

    def _get_logi_frame(self):
        with self._lock_logi:
            return self._frame_logi.copy() if self._frame_logi is not None else None

    # ---- Goal / cancel ------------------------------------------------------

    def goal_callback(self, goal_request):
        self.get_logger().info('Inspection goal received')
        return GoalResponse.ACCEPT

    def cancel_callback(self, goal_handle):
        self.get_logger().info('Cancel requested')
        return CancelResponse.ACCEPT

    # ---- Continuous debug timer --------------------------------------------

    def _debug_timer_cb(self):
        """Runs at 2Hz -- always publishes debug images to RViz."""
        if not self._yolo_lock.acquire(blocking=False):
            return  # YOLO busy with goal, skip this tick
        try:
            insta_frame = self._get_insta_frame()
            logi_frame  = self._get_logi_frame()
            if insta_frame is not None and self.model is not None:
                _, debug = self._detect_raw(insta_frame)
                msg = self.bridge.cv2_to_imgmsg(debug, encoding='bgr8')
                msg.header.stamp = self.get_clock().now().to_msg()
                self.debug_insta_pub.publish(msg)
            if logi_frame is not None and self.model is not None:
                _, debug = self._detect_raw(logi_frame)
                msg = self.bridge.cv2_to_imgmsg(debug, encoding='bgr8')
                msg.header.stamp = self.get_clock().now().to_msg()
                self.debug_logi_pub.publish(msg)
        finally:
            self._yolo_lock.release()

    # ---- Servo helpers ------------------------------------------------------

    def _send_servo(self, tilt, pan):
        msg = Int16MultiArray()
        msg.data = [clamp_servo(tilt), clamp_servo(pan)]
        self.servo_pub.publish(msg)

    def _home_servos(self):
        self._send_servo(90, 90)
        self.get_logger().info('Servos returned to home (90, 90)')

    # ---- Detection ----------------------------------------------------------

    def _detect_raw(self, frame, conf=None):
        """Run YOLO on a frame. Returns (detections, debug_frame). Does NOT lock."""
        if self.model is None or frame is None:
            return [], frame
        threshold = conf if conf is not None else self.YOLO_CONF
        results   = self.model(frame, verbose=False, conf=threshold)[0]
        detections = []
        debug = frame.copy()
        for box in results.boxes:
            x1, y1, x2, y2 = [int(v) for v in box.xyxy[0].tolist()]
            cx  = (x1 + x2) / 2.0
            cy  = (y1 + y2) / 2.0
            c   = float(box.conf[0])
            cls = int(box.cls[0])
            detections.append((cx, cy, x1, y1, x2, y2, c, cls))
            cv2.rectangle(debug, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.circle(debug, (int(cx), int(cy)), 5, (0, 0, 255), -1)
            cv2.putText(debug, f'{c:.2f}', (x1, y1 - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)
        h, w = frame.shape[:2]
        cv2.line(debug, (w//2, 0), (w//2, h), (100, 100, 255), 1)
        cv2.line(debug, (0, h//2), (w, h//2), (100, 100, 255), 1)
        detections.sort(key=lambda d: d[6], reverse=True)
        return detections, debug

    def _detect(self, frame, conf=None):
        """Run YOLO with YOLO lock. Returns (detections, debug_frame)."""
        if frame is None:
            return [], frame
        with self._yolo_lock:
            return self._detect_raw(frame, conf)

    def _detect_insta(self, conf=None):
        frame = self._get_insta_frame()
        if frame is None:
            return [], None
        dets, debug = self._detect(frame, conf)
        msg = self.bridge.cv2_to_imgmsg(debug, encoding='bgr8')
        msg.header.stamp = self.get_clock().now().to_msg()
        self.debug_insta_pub.publish(msg)
        return dets, frame

    def _detect_logi(self, conf=None):
        frame = self._get_logi_frame()
        if frame is None:
            return [], None
        dets, debug = self._detect(frame, conf)
        msg = self.bridge.cv2_to_imgmsg(debug, encoding='bgr8')
        msg.header.stamp = self.get_clock().now().to_msg()
        self.debug_logi_pub.publish(msg)
        return dets, frame

    # ---- IBVS ---------------------------------------------------------------

    def _ibvs_center(self, goal_handle, obj_idx, feedback, start_pan=90.0, start_tilt=90.0):
        """Stage 2: fine IBVS on Logitech frame. Returns True if converged."""
        self.get_logger().info(f'  IBVS centering on Logitech (max {self.IBVS_MAX_ITER} iter)...')

        # PID state
        integral_pan  = 0.0
        integral_tilt = 0.0
        prev_e_pan    = 0.0
        prev_e_tilt   = 0.0

        # Start from coarse position (not home)
        current_pan  = float(start_pan)
        current_tilt = float(start_tilt)

        dt = self.SERVO_DELAY + 0.033  # approx frame interval

        # ---- Wait for first detection in Logitech (servo still moving) ----
        self.get_logger().info(f'  Waiting up to {self.IBVS_FIRST_DET_TIMEOUT}s for object in Logitech...')
        deadline = time.time() + self.IBVS_FIRST_DET_TIMEOUT
        first_det = False
        while time.time() < deadline:
            if goal_handle.is_cancel_requested:
                return False
            dets, _ = self._detect_logi(conf=self.IBVS_CONF)
            if dets:
                first_det = True
                self.get_logger().info('  Object found in Logitech -- starting IBVS loop')
                break
            time.sleep(0.1)

        if not first_det:
            self.get_logger().warn('  Object not visible in Logitech after coarse move -- calibration may need re-tuning')
            return False

        # ---- IBVS loop ----
        for i in range(self.IBVS_MAX_ITER):
            if goal_handle.is_cancel_requested:
                return False

            dets, _ = self._detect_logi(conf=self.IBVS_CONF)
            if not dets:
                self.get_logger().warn(f'  IBVS iter {i}: object lost in Logitech')
                time.sleep(self.SERVO_DELAY)
                continue

            cx_det, cy_det = dets[0][0], dets[0][1]
            ex = cx_det - self.CX_LOGI
            ey = cy_det - self.CY_LOGI
            err = (ex**2 + ey**2) ** 0.5

            feedback.current_step   = 'ibvs'
            feedback.current_object = obj_idx
            feedback.ibvs_error_px  = float(err)
            goal_handle.publish_feedback(feedback)

            if err < self.IBVS_TOL_PX:
                self.get_logger().info(f'  IBVS converged: err={err:.1f}px at iter {i}')
                return True

            # Convert pixel error to angular error
            theta_x = np.degrees(np.arctan(ex / self.FX_LOGI))
            theta_y = np.degrees(np.arctan(ey / self.FY_LOGI))

            # Deadband
            if abs(theta_x) < self.DEADBAND_PX / self.FX_LOGI:
                theta_x = 0.0
            if abs(theta_y) < self.DEADBAND_PX / self.FY_LOGI:
                theta_y = 0.0

            # Sequential: fix pan first, then tilt
            if abs(ex) > self.SLOW_ZONE_PX:
                theta_y = 0.0
                integral_tilt = 0.0

            # PID for pan
            integral_pan = np.clip(integral_pan + theta_x * dt, -50, 50)
            p_pan = self.KP * theta_x
            i_pan = self.KI * integral_pan
            d_pan = self.KD * (theta_x - prev_e_pan) / dt
            delta_pan = -(p_pan + i_pan + d_pan)
            prev_e_pan = theta_x

            # PID for tilt
            integral_tilt = np.clip(integral_tilt + theta_y * dt, -50, 50)
            p_tilt = self.KP * theta_y
            i_tilt = self.KI * integral_tilt
            d_tilt = self.KD * (theta_y - prev_e_tilt) / dt
            delta_tilt = -(p_tilt + i_tilt + d_tilt)
            prev_e_tilt = theta_y

            # Velocity limiting
            speed_scale_pan  = min(1.0, abs(ex) / self.SLOW_ZONE_PX)
            speed_scale_tilt = min(1.0, abs(ey) / self.SLOW_ZONE_PX)
            delta_pan  = np.clip(delta_pan,  -self.MAX_STEP_DEG * speed_scale_pan,
                                              self.MAX_STEP_DEG * speed_scale_pan)
            delta_tilt = np.clip(delta_tilt, -self.MAX_STEP_DEG * speed_scale_tilt,
                                              self.MAX_STEP_DEG * speed_scale_tilt)

            current_pan  = np.clip(current_pan  + delta_pan,  0, 180)
            current_tilt = np.clip(current_tilt + delta_tilt, 20, 160)
            self._send_servo(current_tilt, current_pan)

            if i % 10 == 0:
                self.get_logger().info(f'  IBVS iter {i}: err={err:.1f}px '
                                       f'pan={current_pan:.1f} tilt={current_tilt:.1f}')
            time.sleep(self.SERVO_DELAY)

        self.get_logger().warn('  IBVS timeout')
        return False

    # ---- Image capture ------------------------------------------------------

    def _capture_images(self, n=4):
        images = []
        for i in range(n):
            frame = self._get_logi_frame()
            if frame is not None:
                images.append(frame.copy())
                self.get_logger().info(f'  Captured image {i+1}/{n}')
            time.sleep(self.CAPTURE_DELAY)
        return images

    # ---- MQTT ---------------------------------------------------------------

    def _publish_mqtt(self, images, obj_id):
        try:
            import paho.mqtt.client as mqtt
            import base64
            import json
            BROKER = 'localhost'
            PORT   = 1883
            TOPIC  = f'visual_inspection/object_{obj_id}/images'
            client = mqtt.Client()
            client.connect(BROKER, PORT, timeout=5)
            for i, img in enumerate(images):
                _, buf = cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, 85])
                payload = json.dumps({
                    'object_id': obj_id, 'image_idx': i,
                    'timestamp': time.time(),
                    'image_b64': base64.b64encode(buf.tobytes()).decode()
                })
                client.publish(TOPIC, payload)
            client.disconnect()
            self.get_logger().info(f'  Published {len(images)} images via MQTT')
            return True
        except Exception as e:
            self.get_logger().warn(f'  MQTT skipped: {e}')
            return True  # don't fail inspection just because MQTT is unavailable

    # ---- Main execute -------------------------------------------------------

    def execute_callback(self, goal_handle):
        self.get_logger().info('Starting inspection...')
        self._goal_active = True

        max_objects = goal_handle.request.max_objects
        return_home = goal_handle.request.return_home
        feedback    = InspectObjects.Feedback()
        result      = InspectObjects.Result()

        # Wait for camera frames to arrive
        time.sleep(0.5)

        # ---- Stage 1: detect on Insta360 ----
        feedback.current_step = 'detecting'
        goal_handle.publish_feedback(feedback)

        dets_insta, _ = self._detect_insta()
        if not dets_insta:
            self.get_logger().warn('No objects detected on Insta360')
            if return_home:
                self._home_servos()
            result.success           = False
            result.objects_inspected = 0
            result.failed_reason     = 'no_detection'
            goal_handle.abort()
            return result

        if max_objects > 0:
            dets_insta = dets_insta[:max_objects]

        self.get_logger().info(f'Detected {len(dets_insta)} object(s) on Insta360')

        n_inspected = 0
        for obj_idx, (cx_obj, cy_obj, *_, conf, cls_id) in enumerate(dets_insta, start=1):

            if goal_handle.is_cancel_requested:
                break

            self.get_logger().info(f'Object {obj_idx}: cx={cx_obj:.0f} cy={cy_obj:.0f} conf={conf:.2f}')

            # ---- Coarse positioning (degree-4 formula) ----
            feedback.current_step   = 'coarse'
            feedback.current_object = obj_idx
            goal_handle.publish_feedback(feedback)

            pan_coarse  = calculate_pan(cx_obj, cy_obj)
            tilt_coarse = calculate_tilt(cx_obj, cy_obj)
            self._send_servo(tilt_coarse, pan_coarse)
            self.get_logger().info(f'  Coarse: tilt={tilt_coarse:.1f} pan={pan_coarse:.1f} -- waiting {self.RECENTER_WAIT}s')
            time.sleep(self.RECENTER_WAIT)

            # ---- Stage 2: IBVS on Logitech ----
            feedback.current_step = 'ibvs'
            goal_handle.publish_feedback(feedback)
            centred = self._ibvs_center(goal_handle, obj_idx, feedback,
                                        start_pan=pan_coarse, start_tilt=tilt_coarse)

            if not centred:
                result.success           = False
                result.objects_inspected = n_inspected
                result.failed_reason     = 'ibvs_timeout'
                if return_home:
                    self._home_servos()
                goal_handle.abort()
                return result

            # ---- Capture ----
            feedback.current_step = 'capturing'
            goal_handle.publish_feedback(feedback)
            time.sleep(self.CAPTURE_DELAY)
            images = self._capture_images(self.IMAGES_PER_OBJ)

            # ---- MQTT ----
            feedback.current_step = 'publishing'
            goal_handle.publish_feedback(feedback)
            self._publish_mqtt(images, obj_idx)

            n_inspected += 1
            self.get_logger().info(f'Object {obj_idx} done')

        self._goal_active = False
        if return_home:
            self._home_servos()

        result.success           = True
        result.objects_inspected = n_inspected
        result.failed_reason     = ''
        goal_handle.succeed()
        self.get_logger().info(f'Inspection complete: {n_inspected} object(s)')
        return result


# ---------------------------------------------------------------------------

def main(args=None):
    rclpy.init(args=args)
    node = IBVSActionServer()
    executor = rclpy.executors.MultiThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
